### ISSUE TITLE
Clockwork GameShell: TIC metaclass does not implement music

### ISSUE THREAD

**Issue by dud225** [UnicornsOfDeath/road-txtr#1]
Hello

When launching this game on the GameShell I'm getting the following error:
```
-1, "TIC metaclass does not implement `music(_, _, _, _)`,"
"main", 579 ,"reset()"
"main", 1758 ,"init new()"
"main", 1759 ,""
Error in game class :(
```

According to the information just below this error the GameShell is running TIC-80 version 0.80.0-dev (actually it's a fork catered for the GameShell: https://github.com/cuu/TIC-80)

**Comment by cxong** [comment]
hmm that sucks, they should totally update their TIC-80 version (although I heard version 1 had back compat issues)

**Comment by dud225** [comment]
OK that's what I thought. So closing this issue as the problem doesn't lie here.

**Comment by dud225** [comment]
I've just compiled the latest version of TIC-80 on my GameShell and I can confirm that the game loads fine.
